import { messageHandler } from './messageHandler';
import { codeApply } from './codeApply';
import { codeFileApply } from './codeFileApply';
import { convertCommand } from './convertCommand';
import { doCommit } from './doCommit';
import { historyMessages } from './historyMessages';
import { regCommandList } from './regCommandList';
import { regContextList } from './regContextList';
import { sendMessage } from './sendMessage';
import { blockApply } from './showDiff';
import { showDiff } from './showDiff';
import { addConext } from './addContext';

messageHandler.registerHandler('addContext', addConext);
messageHandler.registerHandler('code_apply', codeApply);
messageHandler.registerHandler('code_file_apply', codeFileApply);
messageHandler.registerHandler('convertCommand', convertCommand);
messageHandler.registerHandler('doCommit', doCommit);
messageHandler.registerHandler('historyMessages', historyMessages);
messageHandler.registerHandler('regCommandList', regCommandList);
messageHandler.registerHandler('regContextList', regContextList);
messageHandler.registerHandler('sendMessage', sendMessage);
messageHandler.registerHandler('block_apply', blockApply);
messageHandler.registerHandler('show_diff', showDiff);